### ISSUE TITLE
Why are mail groups POSIX groups as well?

### ISSUE THREAD

**Issue by martimarkov** [fusiondirectory/fusiondirectory#37]
Is there a reason for this to be the check for mail groups:

    $ldap->search('(&(objectClass=posixGroup)(objectClass=fdGroupMail))', array('cn'));

**Comment by bilbo-the-hobbit** [comment]
hello,

for historical reason, the idea is to put mail group onto your posix groups aso visually is easier.

What do you want to do ?

Cheers

**Comment by martimarkov** [comment]
I was just wondering. Like why not use (groupOfNames || posixGroup) && fdGroupMail?

**Comment by MCMic** [comment]
I guess you are talking about the dashboard it’s the only place I can see this filter.
Indeed there can be mail groups based on groupOfNames, you just need to activate mail tab on a groupOfNames with only users in it.
The dashboard uses this filter because it lists mail groups under posix groups, so if it showed mail groups based on all groups the total would not match.
But maybe this is obsolete and we should just show the total number of mailgroups, not sure.

**Comment by MCMic** [comment]
My bad the filter in group management also uses this.
It’s because for groups there is only one checkbox while for posix groups there was several possibilities historically.
Not sure if we should fix this and how.

**Comment by bilbo-the-hobbit** [comment]
Hello,

since the migration to gitlab this is the link of the ticket

Cheers
