### ISSUE TITLE
Install fusiondirectory with Zimbra OpenLDAP

### ISSUE THREAD

**Issue by s33k3rs** [fusiondirectory/fusiondirectory#62]
i have installed fusiondirectory uses existing external Zimbra OpenLDAP, but when connecting between them I get an error:

`root@fd:/usr/share# fusiondirectory-setup --check-config
Checking FusionDirectory's config file
/etc/fusiondirectory/fusiondirectory.conf exists…
Rights on /etc/fusiondirectory/fusiondirectory.conf are correct
root@fd:/usr/share# fusiondirectory-setup --check-ldap
Checking your LDAP tree
! There is no admin ACL role
No valid admin account found, do you want to create it ? [Yes/No]?
Yes
Could not find configuration object, using default value
Please enter a login for FusionDirectory's admin [fd-admin]:
fd-admin
User fd-admin already existing, adding admin acl to it

! failed to add LDAP's cn=admin,ou=aclroles,dc=xxxxxxxxxx,dc=xx,dc=xx entry - LDAP_UNDEFINED_TYPE: The request contains an undefined attribute type
root@fd:/usr/share#
`

**Comment by bilbo-the-hobbit** [comment]
Hello @s33k3rs 

We don't officially support the OpenLDAP from zimbra because its heavily customized for zimbra itself.

did you follow the official documentation on how to install FusionDirectory https://fusiondirectory-user-manual.readthedocs.io/en/1.3/fusiondirectory/install/index.html

Check all the step to be sure you didn't forgot something

Cheers
