### ISSUE TITLE
Debian Bookworm package

### ISSUE THREAD

**Issue by Trylam** [fusiondirectory/fusiondirectory#80]
Debian Bookworm currently has no package for fusion-directory.
Support for fusion-directory has apparently been removed from debian.

**Comment by bilbo-the-hobbit** [comment]
Hello @Trylam 

There is no support for debian Bookworm in FusionDirectory now. The removal was planned as its to difficult to synchronize the release of FusionDirectory and Debian

the supported Distribution list is here : https://www.fusiondirectory.org/en/certified-distributions/

Cheers

**Comment by Trylam** [comment]
Where can I find the sources for the fusiondirectory 1.4 package for Debian Buster so that I can use it to port Fusion Directory to Bookworm?

**Comment by HumanG33k** [comment]
Their is several small companies and non-profit org that can not afford support and will not use ubuntu because of the gouvernance and bad choices made by amazon. Their is no way to setup a CI pipeline on your own gitlab in order to build it for debian or organise release based on debian ~ 2 years release cycle. It can be the best solution even for your own customers, few maintenances for them and more automatisation. And permit to improve QA and make clear roadmap ? Is there is something i miss ?
